baseurl: "/guiadeti"
url: ""

collections:
  areas:
    output: true
  guides:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: areas
    values:
      layout: "content"
  - scope:
      path: ""
      type: guides
    values:
      layout: "content"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag