baseurl: "/guiadeti"
url: ""

collections:
  areas:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: areas
    values:
      layout: "area"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag